CREATE DATABASE QuanLiBanHang
GO
USE QuanLiBanHang
GO
-----------------------------Bài 1---------------------------------
CREATE TABLE KHACHHANG (
	MAKH CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	DOANHSO SMALLDATETIME,
	NGDK MONEY,
	CONSTRAINT PK_KH PRIMARY KEY(MAKH)
)
CREATE TABLE NHANVIEN (
	MANV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	NGVL VARCHAR(20),
	SODT SMALLDATETIME,
	CONSTRAINT PK_NV PRIMARY KEY(MANV)
)
CREATE TABLE SANPHAM (
	MASP CHAR(4) NOT NULL,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY,
	CONSTRAINT PK_SP PRIMARY KEY(MASP)
)
CREATE TABLE HOADON (
	SOHD INT NOT NULL,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) REFERENCES dbo.KHACHHANG(MAKH),
	MANV CHAR(4) REFERENCES dbo.NHANVIEN(MANV),
	TRIGIA MONEY,
	CONSTRAINT PK_HD PRIMARY KEY(SOHD)
)
CREATE TABLE CTHD (
	SOHD INT REFERENCES dbo.HOADON(SOHD),
	MASP CHAR(4) REFERENCES dbo.SANPHAM(MASP),
	SL INT
)
-----------------------------Bài 2---------------------------------
--Câu 2:
ALTER TABLE dbo.SANPHAM ADD GHICHU VARCHAR(20)
--Câu 3:
ALTER TABLE dbo.KHACHHANG ADD LOAIKH TINYINT
--Câu 4:
ALTER TABLE dbo.SANPHAM ALTER COLUMN GHICHU VARCHAR(100)
--Câu 5:
ALTER TABLE dbo.SANPHAM DROP COLUMN GHICHU
--Câu 6:
ALTER TABLE dbo.KHACHHANG ALTER COLUMN LOAIKH VARCHAR(20)
--Câu 7:
ALTER TABLE dbo.SANPHAM ADD CONSTRAINT SP_CHECK CHECK(DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'))
--Câu 8:
ALTER TABLE dbo.SANPHAM ADD CONSTRAINT GIA_CHECK CHECK(GIA>500)
--Câu 9:
ALTER TABLE dbo.CTHD ADD CONSTRAINT SL_CHECK CHECK(SL>1)
--Câu 10:
ALTER TABLE dbo.KHACHHANG ADD CONSTRAINT NGDK_CHECK CHECK(NGDK>NGSINH)