CREATE DATABASE QuanLyGiaoVu
GO
USE QuanLyGiaoVu
GO
-----------------------------Bài 1---------------------------------
CREATE TABLE KHOA (
	MAKHOA VARCHAR(4) NOT NULL,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4),
	CONSTRAINT PK_MK PRIMARY KEY(MAKHOA)
)

CREATE TABLE MONHOC (
	MAMH VARCHAR(10) NOT NULL,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4) REFERENCES dbo.KHOA(MAKHOA)
	CONSTRAINT PK_MH PRIMARY KEY(MAMH)
)
CREATE TABLE DIEUKIEN (
	MAMH VARCHAR(10) REFERENCES dbo.MONHOC(MAMH),
	MAMH_TRUOC VARCHAR(10) REFERENCES dbo.MONHOC(MAMH)
	CONSTRAINT PK_DK PRIMARY KEY(MAMH, MAMH_TRUOC)
)
CREATE TABLE GIAOVIEN (
	MAGV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4) REFERENCES dbo.KHOA(MAKHOA),
	CONSTRAINT PK_GV PRIMARY KEY(MAGV)
)
CREATE TABLE LOP (
	MALOP CHAR(3) NOT NULL,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4) REFERENCES dbo.GIAOVIEN(MAGV)
	CONSTRAINT PK_ML PRIMARY KEY(MALOP)
)
CREATE TABLE HOCVIEN (
	MAHV CHAR(5) NOT NULL,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3) REFERENCES dbo.LOP(MALOP)
	CONSTRAINT PK_HV PRIMARY KEY(MAHV)
)
CREATE TABLE GIANGDAY (
	MALOP CHAR(3) REFERENCES dbo.LOP(MALOP),
	MAMH VARCHAR(10) REFERENCES dbo.MONHOC(MAMH),
	MAGV CHAR(4) REFERENCES dbo.GIAOVIEN(MAGV),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME, 
	DENNGAY SMALLDATETIME
)
CREATE TABLE KETQUATHI (
	MAHV CHAR(5) REFERENCES dbo.HOCVIEN(MAHV),
	MAMH VARCHAR(10) REFERENCES dbo.MONHOC(MAMH),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10)
)
-----------------------------Bài 3---------------------------------
--Bài 2:
ALTER TABLE dbo.HOCVIEN ADD CONSTRAINT CHECK_MAHV CHECK (LEN(MAHV)=5 AND SUBSTRING(MAHV, 1, 3)=MALOP AND ISNUMERIC(SUBSTRING(MAHV, 4, 5))=1)
-------------------------------------------------------  Độ dài chuổi là 5 -- so sánh 3 kí tự đầu với mã lớp ---- 2 kí tự cuối có phải là số không
--Bài 3:
--Kiểm tra giới tính giáo viên, học viên
ALTER TABLE dbo.GIAOVIEN ADD CONSTRAINT CHECK_GTGV CHECK( GIOITINH IN ('Nam', 'Nu'))
ALTER TABLE dbo.HOCVIEN ADD CONSTRAINT CHECK_GTHV CHECK( GIOITINH IN ('Nam', 'Nu'))
--Bài 4:
ALTER TABLE dbo.KETQUATHI ADD CONSTRAINT CHECK_KQT CHECK( DIEM BETWEEN 0 AND 10)
--- Kiểu dữ liệu của DIEM đã quy định là số nhập vào có 2 cố ở phần thập phân
--Bài 5:
ALTER TABLE dbo.KETQUATHI ADD CONSTRAINT CHECK_DIEM CHECK( (KQUA='Dat' AND DIEM BETWEEN 5 AND 10) OR (DIEM BETWEEN 0 AND 5 AND KQUA='Khong dat'))
--Bài 6:
ALTER TABLE dbo.KETQUATHI ADD CONSTRAINT CHECK_LT CHECK(LANTHI<=3)
--Bài 7:
ALTER TABLE dbo.GIANGDAY ADD CONSTRAINT CHECK_HK CHECK(HOCKY BETWEEN 1 AND 3)
--Bài 8:
ALTER TABLE dbo.GIAOVIEN ADD CONSTRAINT CHECK_HV CHECK(HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))